### ISSUE TITLE
Crash in VCV using the Rotate knob

### ISSUE THREAD

**Issue by W4too** [phestrada/OME#1] opened 2024-06-23 17:25 UTC
Hi,

I'm using Damonitu moving few parameters : density, pattern and octave (with Stoermelder Transit to get discrete values).
All is working fine until i'm starting to play with the Rotate knob, resulting with a crash in VCV.

![1](https://github.com/phestrada/OME/assets/100092785/d8b2f1f9-47a7-46d0-8bd5-ab28699e177e)

**Comment by phestrada** [comment] 2024-06-24 10:46
Hi.

I was able to reproduce the crash. I'm working in it. As you wrote, the problem is directly related, in some specific cases, to the calculation of the rotation offset. Will be an update soon.

Thanks.

**Comment by W4too** [comment] 2024-06-24 16:08
HI,
I was about to post the stack trace but glad to read that you solved it. ^^
Thanks

**Comment by phestrada** [comment] 2024-06-26 09:36
Hi.

Fixed in version 2.2.0. I think the new plugin will be published soon in VCV library . 

Thanks.

**Comment by phestrada** [comment] 2024-06-26 09:38
.

**Comment by phestrada** [comment] 2024-06-26 09:38
Hi.

Fixed in version 2.2.0. I think the new plugin will be published soon in VCV library .

Thanks.

**Closed as completed by phestrada** 2024-06-26 09:38 UTC
